### ISSUE TITLE
Разнести данные по проектам

### ISSUE THREAD

**Issue by AshNaMassu** [sloruslan/Life#3]
Например, в данный момент Cell содержит Color и Brushes, что, вроде как, является скорее часть моделью отображения, то есть клиентского приложения.
Да и клиентское приложение напрямую обращается к методам генерации, которые реализованы для серверной части. От этого необходимо будет уйти, оставив клиенту только данные для отображения. Ну, для этого необходимо реализовывать пробуферы
и занимать клиент только настройкой сервера и отображением данных. 
Собственно, сервер тоже надо реализовать так, чтобы он выполнял вычисления, а не только предоставлял методы.
Ну пока так
![issue](https://user-images.githubusercontent.com/107715588/174895738-2f8425fb-95f0-4a33-9208-00159123a56c.JPG)

**Comment by sloruslan** [comment]
Красава😎
